<?php

/**
 * @file
 * Main file for the happy_new_year module.
 */

/**
 * Implements hook_menu().
 */
function happy_new_year_menu() {
  $items['admin/config/media/happy_new_year'] = [
    'title' => 'Happy New Year!',
    'description' => 'A module with garland and snow decoration that creates longlasting atmosphere of New Year for you and the users of your website.',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['happy_new_year_settings_form'],
    'access arguments' => ['administer site configuration'],
  ];

  return $items;
}

/**
 * Form settings.
 */
function happy_new_year_settings_form() {
  $days = [];
  for ($i = 1; $i <= 31; $i++) {
    $days[] = $i;
  }

  $form = [];
  $form['period'] = [
    '#type' => 'fieldset',
    '#title' => t('Working period'),
  ];
  $form['period']['happy_new_year_period'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable working period'),
    '#default_value' => variable_get('happy_new_year_period', FALSE),
    '#description' => t('If the working period is not specified, the module will run all the time'),
  ];
  $form['period']['period_dates'] = [
    '#type' => 'fieldset',
    '#title' => t('Select start date and end date'),
    '#states' => [
      'visible' => [
        '#edit-happy-new-year-period' => ['checked' => TRUE],
      ],
    ],
  ];
  $form['period']['period_dates']['happy_new_year_start'] = [
    '#type' => 'select',
    '#title' => t('Start day (december)'),
    '#options' => $days,
    '#default_value' => variable_get('happy_new_year_start', 1),
  ];
  $form['period']['period_dates']['happy_new_year_end'] = [
    '#type' => 'select',
    '#title' => t('End day (january)'),
    '#options' => $days,
    '#default_value' => variable_get('happy_new_year_end', 10),
  ];
  $form['snow_and_garland'] = [
    '#type' => 'fieldset',
    '#title' => t('Garland and Snow'),
  ];
  $form['snow_and_garland']['happy_new_year_garland'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable garland'),
    '#default_value' => variable_get('happy_new_year_garland', FALSE),
  ];
  $form['snow_and_garland']['garland_settings'] = [
    '#type' => 'fieldset',
    '#title' => t('Garland settings'),
    '#states' => [
      'visible' => [
        '#edit-happy-new-year-garland' => ['checked' => TRUE],
      ],
    ],
  ];
  $form['snow_and_garland']['garland_settings']['happy_new_year_garland_position'] = [
    '#type' => 'checkbox',
    '#title' => t('Top-Fixed garland'),
    '#default_value' => variable_get('happy_new_year_garland_position', TRUE),
  ];
  $form['snow_and_garland']['happy_new_year_snow'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable snow'),
    '#default_value' => variable_get('happy_new_year_snow', FALSE),
  ];
  $form['snow_and_garland']['snow_settings'] = [
    '#type' => 'fieldset',
    '#title' => t('Snow settings'),
    '#states' => [
      'visible' => [
        '#edit-happy-new-year-snow' => ['checked' => TRUE],
      ],
    ],
  ];
  $form['snow_and_garland']['snow_settings']['happy_new_year_snowcolor'] = [
    '#type' => 'textfield',
    '#title' => t('Snow color'),
    '#suffix' => '<div id="color-picker"></div>',
    '#default_value' => variable_get('happy_new_year_snowcolor', '#FFFFFF'),
    '#maxlength' => 7,
    '#size' => 7,
    '#attached' => [
      'library' => [['system', 'farbtastic']],
      'js' => [drupal_get_path('module', 'happy_new_year') . '/js/colorpicker.js'],
    ],
  ];
  $form['happy_new_year_minified'] = [
    '#type' => 'checkbox',
    '#title' => t('Use minified libraries if it possible'),
    '#default_value' => variable_get('happy_new_year_minified', TRUE),
  ];
  return system_settings_form($form);
}

/**
 * Helper function.
 *
 * @return bool
 */
function _happy_new_year_isholidaytime() {
  $start = variable_get('happy_new_year_start') +1 ;
  $end = variable_get('happy_new_year_end') + 1;

  if(date('m') == 12 && date('d') >= $start){
    return TRUE;
  }
  else if(date('m') == 1 && date('d') <= $end){
    return TRUE;
  }
  else{
    return FALSE;
  }
}

/**
 * Implements hook_page_build().
 */
function happy_new_year_page_build(&$page) {
  if ((variable_get('happy_new_year_period')) && !_happy_new_year_isholidaytime()) {
    return;
  }

  if ((!path_is_admin(current_path()))) {
    $snowLibrary = '/js/snowstorm.js';
    $snowLibraryMin = '/js/snowstorm-min.js';
    if (variable_get('happy_new_year_minified', TRUE)) {
      $snowLibrary = $snowLibraryMin;
    }
    if (variable_get('happy_new_year_garland')) {
      drupal_add_js(drupal_get_path('module', 'happy_new_year') . '/js/garland.js');
      drupal_add_css(drupal_get_path('module', 'happy_new_year') . '/css/garland.css');
      if (variable_get('happy_new_year_garland_position', TRUE)) {
        drupal_add_css(drupal_get_path('module', 'happy_new_year') . '/css/garland-fixed.css');
      }
      else {
        drupal_add_css(drupal_get_path('module', 'happy_new_year') . '/css/garland-absolute.css');
      }
    }
    if (variable_get('happy_new_year_snow')) {
      drupal_add_js(drupal_get_path('module', 'happy_new_year') . $snowLibrary);
      drupal_add_js(drupal_get_path('module', 'happy_new_year') . '/js/snow.js');
      drupal_add_js(['happy_new_year' => ['snowColor' => variable_get('happy_new_year_snowcolor', '#FFFFFF')]], ['type' => 'setting']);
    }
  }
}

/**
 * Implements hook_help().
 */
function happy_new_year_help($path, $arg) {
  return '';
}
